### PR TITLE
Nc region

### PR DESCRIPTION
**Pull request by huard**
Allows clip and aggregate operations with netCDF4 output.

### CODE REVIEW

**Comment by bstdenis** [comment]
Is there an example somewhere of the call you make to do the spatial averaging? I get an error that ocgis_spatial_mask does not exist, is there an option to create it that I need to specify?

my call is :

ops = ocgis.OcgOperations(dataset=rd, geom=[100, -10, 110, -8],
                                  spatial_operation='clip', aggregate=True,
                                  snippet=False, output_format='region-nc',
                                  interpolate_spatial_bounds=True,
                                  prefix='nc_output').execute()

I get :

Traceback (most recent call last):
  File "test_ocgis.py", line 307, in test_spatial_weighted_average_01
    prefix='nc_output').execute()
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/ops/core.py", line 313, in execute
    return interp.execute()
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/ops/interpreter.py", line 135, in execute
    ret = conv.write()
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/conv/nc.py", line 283, in write
    field.remove_variable('ocgis_spatial_mask')
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/variable/base.py", line 1891, in remove_variable
    variable = get_variables(variable, self)[0]
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/base.py", line 175, in get_variables
    ret[idx] = parent[n]
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/variable/base.py", line 1539, in __getitem__
    ret = AbstractCollection.__getitem__(self, item_or_slc)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/collection/base.py", line 34, in __getitem__
    return self._storage[item]
KeyError: 'ocgis_spatial_mask'

**Comment by huard** [comment]
I suspect there is no spatial_mask generated from your file. I'll put the
remove call in a try statement.

**Comment by huard** [comment]
Pushed fix. Untested.

**Comment by bstdenis** [comment]
Works on pure NetCDF4 files, NETCDF4_CLASSIC fails with :

Traceback (most recent call last):
  File "test_ocgis.py", line 678, in test_spatial_weighted_average_04b
    prefix='nc_output').execute()
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/ops/core.py", line 313, in execute
    return interp.execute()
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/ops/interpreter.py", line 135, in execute
    ret = conv.write()
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/conv/nc.py", line 359, in write
    self._write_coll_(f, coll)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/conv/nc.py", line 192, in _write_coll_
    self._write_archetype_(arch, ds, self._variable_kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/conv/nc.py", line 236, in _write_archetype_
    arch.write(path, **write_kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/collection/field.py", line 930, in write
    return driver.write_field(*args, **kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/driver/base.py", line 527, in write_field
    cls.write_variable_collection(vc_to_write, opened_or_path, **kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/driver/base.py", line 551, in write_variable_collection
    cls._write_variable_collection_main_(vc, opened_or_path, write_mode, **kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/driver/nc.py", line 197, in _write_variable_collection_main_
    variable.write(dataset, write_mode=write_mode, **variable_kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/variable/base.py", line 1358, in write
    driver.write_variable(*args, **kwargs)
  File "/home/stdenis/projects/pavics/from_huard/git/ocgis/src/ocgis/driver/nc.py", line 133, in write_variable
    ncvar = dataset.createVariable(var.name, dtype, dimensions=dimensions, fill_value=fill_value, **kwargs)
  File "netCDF4/_netCDF4.pyx", line 2196, in netCDF4._netCDF4.Dataset.createVariable (netCDF4/_netCDF4.c:16626)
  File "netCDF4/_netCDF4.pyx", line 3090, in netCDF4._netCDF4.Variable.__init__ (netCDF4/_netCDF4.c:28059)
RuntimeError: NetCDF: Attempting netcdf-4 operation on strict nc3 netcdf-4 file

**Comment by bstdenis** [comment]
Also, not really a bug, but the returned longitudes seem forced between -180 to 180, even if the original file (& polygon) are specified in the 0-360 range.

**Comment by huard** [comment]
Envoie-moi ton test, je vais voir ce que je peux faire.

**Comment by bstdenis** [comment]
C'est bon, ça fonctionne! :+1:

**Pull request merged**
